#!/usr/bin/env node

var postcss = require('postcss')
var path = require('path')
var fs = require('fs')

var jsonify = require('./jsonify')
var cases = path.join(__dirname, 'cases')
var extra = require('./extra-cases')

var dev = path.join(__dirname, '..', 'postcss', 'build', 'package.json')
if (fs.existsSync(dev)) {
  process.stdout.write('Using development version of PostCSS\n')
  postcss = require('../postcss/build')
}

function read (file) {
  return fs.readFileSync(path.join(cases, file)).toString()
}

fs.readdirSync(cases).forEach(function (i) {
  if (path.extname(i) !== '.json') return
  var name = path.basename(i, '.json')
  var css = extra[name]
  if (!css) css = read(name + '.css').trim()
  var root = postcss.parse(css, { from: '/' + name + '.css' })
  fs.writeFileSync(path.join(cases, name + '.json'), jsonify(root) + '\n')
  process.stdout.write('.')
})

process.stdout.write('\n')
